### ISSUE TITLE
＜ロールプレイング＞のコンテキストと問題と具体例

### ISSUE THREAD

**Issue by irohiroki** [krayinc/kray_patterns#5]
＜[ロールプレイング](https://github.com/krayinc/kray_patterns/blob/f2ba06d1d0c1cc2b1a8932ce3d9e49701f51fbb3/patterns/role_playing.md)＞、原稿は"プロジェクトの進行がストップしないように協力しよう"という内容だったんですが（原稿を持ってる人は共有してもらえると助かります）、元の付箋には問題を書いたものがなく、下のようになっていました：
- Solution: 個性を活かして協力する
- Action: お互いをきちんと承認する
- Action: 自分の強みを知る
- Consequence: 各自が活躍できる

つまりプロジェクトの進行の問題とは限らず、仕事に対する満足度や、メンバー同士の関係の話に見えます。

そこで、どんな問題を設定したら自然か、どんなActionをすべきか（しているか）を考えてもらえないでしょうか？

**Comment by asachun** [comment]
元々は「全員がすべての作業ができたらいいけど、やっぱり人によってどうしても苦手なこと得意なことはあるので、そのあたりチームでうまくカバーし合いながら仕事できたらいいよね」という話だった気がします。

> つまりプロジェクトの進行の問題とは限らず、仕事に対する満足度や、メンバー同士の関係の話に見えます。

こちらはわたしもそういう風に見えます。
苦手なことを嫌々やってるとモチベーションも上がりませんし、時間もかかるので、そのあたりはメンバーの個々の能力をきちんと把握して、なるべく各人が得意なことをできたらプロジェクトの進行もスムーズになるしみんな幸せになれますよね。（そうはいかないことはよくあるでしょうが）

問題としては「役割分担が不適切で、メンバーやチームのモチベーションが下がる」などでしょうか。

**Comment by amano** [comment]
元々の原稿はこれかな？
https://www.dropbox.com/s/u1ns3g2kps2aqbr/20140904_KRAY%E3%83%91%E3%82%BF%E3%83%BC%E3%83%B3.pdf?dl=0

この原稿に書かれている問題は次の通りです。
**個人の問題がチーム全体の問題になる**

**Comment by amano** [comment]
役割分担が不適切だと、モチベーションが下がるし、仕事の質が低くなることが問題だと思いました。
あさちゅんの書いたものに仕事の質についても加えるのはどうでしょう？

役割分担が不適切の場合、仕事の質も下がり、メンバーのモチベーションも下がる

うまい書き方ができません。。

**Comment by irohiroki** [comment]
フィードバックありがとう！参考にして書き直し、「プロジェクト進行」の話を外して「モチベーション」や「仕事の質」を意識した文に[しました](https://github.com/krayinc/kray_patterns/blob/466992addd82f75bd76d41e74349efea939f6c56/patterns/role_playing.md#%E3%83%AD%E3%83%BC%E3%83%AB%E3%83%97%E3%83%AC%E3%82%A4%E3%83%B3%E3%82%B0)。

……した後に気づいたんですが、これって[アンサンブルチーム](https://github.com/krayinc/kray_patterns/blob/master/patterns/ensemble_team.md#%E3%82%A2%E3%83%B3%E3%82%B5%E3%83%B3%E3%83%96%E3%83%AB%E3%83%81%E3%83%BC%E3%83%A0)にまとめたパターンだったかもしれない…。結果的にアンサンブルチームより良く書けたので、こちらの文を中心にまとめ直そうと思います。

**Comment by asachun** [comment]
@irohiroki すごくよくなったと思います！

[![LGTM](http://lgtm.in/p/g21zr0N7q)](http://lgtm.in/i/g21zr0N7q)

**Comment by irohiroki** [comment]
いいLGTM!!!! ありがとう!!!!!!

**Comment by ishizima** [comment]
[![:+1:](http://lgtm.in/p/kycNJ9leq)](http://lgtm.in/i/kycNJ9leq)

**Comment by irohiroki** [comment]
これもいいLGTM!!! 涙なしでは見られませんでした!!!!!
